### ISSUE TITLE
Add Economy endpoints

### ISSUE THREAD

**Issue by tannerz28** [Nightwatch/api#35]

**Comment by tannerz28** [comment]
Need an endpoint for transferring credits from one user to another. Currently to do so, you have to make two requests, one to update each users balance.
I'm thinking the route would be `/user/:id/balance/transfer/:receiverId` It would accept an object `{ fromId: string, fromBalance: UserBalance, toId: string, toBalance: UserBalance }`

**Comment by jasonhaxstuff** [comment]
Would the request have a body like this:
```JSON
{ "amount": 50 }
```

**Comment by tannerz28** [comment]
Yep.

**Comment by jasonhaxstuff** [comment]
What should I do if the user doesn't have enough balance?
