### ISSUE TITLE
Add endpoint to get Users in a Guild by Guild ID

### ISSUE THREAD

**Issue by tannerz28** [Nightwatch/api#5]
Create endpoint in Guild controller/service to get all users in a Guild by Guild ID. Don't include any related Guild information (Ignore tables with foreign key to Guild)

**Comment by jasonhaxstuff** [comment]
Would it be something like `${apiurl}/api/guilds/${id}/users`?

**Comment by tannerz28** [comment]
Before the API changes could be made, a new table in the database would need to be created called "GuildMember" or "GuildUser".

The Guild table would need to be modified to also include a OneToMany relation to the new table, the new table would need a ManyToOne relation to the Guild table and a ManyToOne relation on the User table, and the User table would need a OneToMany relation on on the new table. 

Then once those changes are made, the api route would be exactly what you posted: `/api/guilds/:id/users`

It would also be beneficial to have an api route to see if a user is in a guild with the route: `/api/guilds/:id/users/:userId` which would return the user if they exist.

**Comment by jasonhaxstuff** [comment]
Would a `GuildUser` just have the same properties as a normal `User`?

**Comment by tannerz28** [comment]
This is the related database issue for this: https://github.com/NightwatchBot/db/issues/3
